#!/bin/sh
poetry export -f requirements.txt --output requirements.txt --extras all --without-hashes
poetry export -f requirements.txt --output requirements-dev.txt --with dev --without-hashes
git add requirements.txt requirements-dev.txt
